import { useState, useRef, useEffect, useCallback } from "react";
import { motion } from "framer-motion";
import {
  Briefcase,
  ArrowRight,
  Mail,
  Play,
  Clock,
  DollarSign,
  Film,
  TrendingDown,
  Sparkles,
  Target,
  TrendingUp,
  Package,
  Tag,
  Monitor,
  Layers,
  FlaskConical,
  CheckCircle2,
  XCircle,
  Gauge,
  Upload,
  ScanSearch,
  BarChart3,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Footer } from "@/components/Footer";
import { SceneComparisonSlider } from "@/components/SceneComparisonSlider";
import logoUrl from "@assets/fullscale-logo_1767679525676.png";

import heroVideoUrl from "@assets/brands_hero_loop.mp4";
import heroVideoMobileUrl from "@assets/brands_hero_loop_mobile.mp4";

// Scene pairs for the "See it in action" showcase — three purpose-built
// "clean augmentation" pairs generated specifically for /brands. Each pair
// is the same scene with ONLY a product and its shadow added in the
// augmented version, matching the quality bar set by the Landing page's
// kitchen/Boxed Water pair. Generated by Replit Agent in commit d43626b.
import sceneKitchenReality from "@assets/generated_images/brands_kitchen_reality.png";
import sceneKitchenAugmented from "@assets/generated_images/brands_kitchen_augmented.png";
import sceneDjReality from "@assets/generated_images/brands_dj_reality.png";
import sceneDjAugmented from "@assets/generated_images/brands_dj_augmented.png";
import sceneGamerReality from "@assets/generated_images/brands_gamer_reality.png";
import sceneGamerAugmented from "@assets/generated_images/brands_gamer_augmented.png";

/**
 * FullScale For Brands landing page.
 *
 * Full-page brand-facing marketing site. Five beats:
 *   1. Hero — 4-scene video loop (podcast / DJ / gaming / kitchen) with
 *      hero copy and dual CTAs ("Sign Up Now" + "See How It Works")
 *   2. Friction comparison — traditional brand-talent path vs FullScale path,
 *      side-by-side cards
 *   3. Capabilities — four placement types (physical product / stickers /
 *      on-screen overlays / ambient branding)
 *   4. Test-and-learn — three-card row explaining pre-commit validation
 *      (match → A/B → measure-and-scale)
 *   5. Sign-up CTA — final push to the brand signup flow
 *
 * Hero video pattern mirrors FullScaleCreates.tsx exactly (Vite @assets
 * imports for desktop + mobile variants, ref callback for iOS autoplay,
 * videoFailed fallback, window.matchMedia breakpoint switching).
 */

// Brand partners shown in the marquee strip. Logos live in
// client/public/brand-logos/{slug}.png and are served at /brand-logos/{slug}.png.
// If a logo PNG is missing, the <img onError> handler replaces it with the
// brand name rendered as styled text so the section never breaks.
const BRAND_PARTNERS = [
  { slug: "just-water", name: "JUST Water" },
  { slug: "naturade", name: "Naturade" },
  { slug: "shinju", name: "Shinju Japanese Whisky" },
  { slug: "vegan-smart", name: "VeganSmart" },
] as const;

const FRICTION_TRADITIONAL = [
  { icon: Clock, text: "Spend weeks sourcing and vetting creator talent" },
  { icon: DollarSign, text: "Negotiate rates, contracts, and exclusivity terms" },
  { icon: Film, text: "Fund production, travel, reshoots, revisions" },
  { icon: TrendingDown, text: "Launch one spot and hope the impressions land" },
];

const FRICTION_FULLSCALE = [
  { icon: Sparkles, text: "Pick content that already has proven engagement" },
  { icon: Target, text: "Our AI matches your product to contextually-relevant surfaces" },
  { icon: FlaskConical, text: "Test placements across multiple creators at once" },
  { icon: TrendingUp, text: "Scale only the variants that actually perform" },
];

const CAPABILITIES = [
  {
    icon: Package,
    title: "Physical Products",
    description:
      "Drop beverages, electronics, beauty, lifestyle, or food & bev onto a creator's desk, counter, or studio table with AI-perfect lighting and occlusion.",
  },
  {
    icon: Tag,
    title: "Branded Stickers & Decals",
    description:
      "Place your logo or campaign art on a DJ controller, laptop, helmet, or instrument case — wherever your brand fits the moment.",
  },
  {
    icon: Monitor,
    title: "On-Screen Overlays",
    description:
      "Replace a creator's monitor content with your app UI, game preview, or product demo. Perfectly tracked across every frame.",
  },
  {
    icon: Layers,
    title: "Ambient Branding",
    description:
      "Wall art, posters, neon signs, book spines — the subtle placements that build brand presence without breaking the creator's moment.",
  },
];

const SHOWCASE_SCENES = [
  {
    label: "Kitchen",
    sceneNumber: "Scene 1 of 3",
    description:
      "A warm minimalist kitchen — oak counter, sage cabinets, copper pans, morning light from the window. Drag the slider to see our AI place an Olipop can onto the counter with shadow direction matched to the window light and the counter's wood grain preserved right up to the can's base.",
    reality: sceneKitchenReality,
    augmented: sceneKitchenAugmented,
    realityAlt: "Warm minimalist kitchen with oak counter, copper pans, morning window light",
    augmentedAlt: "Same kitchen with an Olipop can placed on the counter by FullScale AI",
    testId: "showcase-kitchen",
  },
  {
    label: "DJ Booth",
    sceneNumber: "Scene 2 of 3",
    description:
      "A DJ controller mid-session — jog wheels, mixer faders, RGB performance pads glowing purple and cyan. Drag to reveal an energy drink can placed on the surface beside the mixer. The can's shadow falls in the direction of the booth's ambient lighting, and its scale matches the controller's depth of field perfectly.",
    reality: sceneDjReality,
    augmented: sceneDjAugmented,
    realityAlt: "DJ controller close-up with jog wheels, mixer faders, and RGB pads",
    augmentedAlt: "Same DJ booth with an energy drink can placed beside the mixer",
    testId: "showcase-dj",
  },
  {
    label: "Gaming Setup",
    sceneNumber: "Scene 3 of 3",
    description:
      "A gaming desk at dusk — dual monitors, mechanical RGB keyboard, desk mat with RGB underglow, gaming chair blurred in the background. Drag to see a Monster Energy can land to the left of the keyboard. The can picks up the warm RGB light in its reflections and drops a clean shadow across the desk surface.",
    reality: sceneGamerReality,
    augmented: sceneGamerAugmented,
    realityAlt: "Gaming desk with dual monitors, RGB keyboard, and accent lighting",
    augmentedAlt: "Same gaming desk with a Monster Energy can placed beside the keyboard",
    testId: "showcase-gamer",
  },
];

const PLACEMENT_STEPS = [
  {
    icon: Upload,
    step: "Step 1",
    title: "You upload your product",
    description:
      "Drop in a clean PNG of your product — drinks, electronics, beauty, apparel, anything with a recognizable silhouette. Add brand guidelines, placement preferences, and which markets you want to reach.",
  },
  {
    icon: ScanSearch,
    step: "Step 2",
    title: "Our AI scans creator content",
    description:
      "FullScale's surface engine analyzes the existing videos in your matched creators' libraries. Every flat surface, every empty frame, every moment your product could live in — identified, scored, and ranked.",
  },
  {
    icon: CheckCircle2,
    step: "Step 3",
    title: "You approve the placements",
    description:
      "Review AI-generated composites before anything goes live. Approve the ones that fit your brand, reject the ones that don't. No surprises, no off-brand moments, no creator-product mismatches.",
  },
  {
    icon: BarChart3,
    step: "Step 4",
    title: "Measure, iterate, scale",
    description:
      "Performance data comes in — engagement per second, view-through rate, purchase-link clicks. Double down on the creators and formats that work. Kill the rest. Scale only what's proven.",
  },
];

const TEST_AND_LEARN = [
  {
    icon: Target,
    title: "Match products to creators",
    description:
      "Run the same product across multiple creators' existing content libraries. See which audience engages most before you commit a dollar.",
  },
  {
    icon: FlaskConical,
    title: "A/B placement variants",
    description:
      "Same video, two surfaces, two product treatments. Find the variant that converts before you commit to a full flight.",
  },
  {
    icon: Gauge,
    title: "Measure and scale",
    description:
      "Engagement per second, view-through rate, click-through for purchase-linked placements. The signal you need to double down on what works.",
  },
];

export default function Brands() {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const [videoFailed, setVideoFailed] = useState(false);
  const [isMobile, setIsMobile] = useState(() =>
    typeof window !== "undefined" && window.matchMedia("(max-width: 768px)").matches
  );

  useEffect(() => {
    const mq = window.matchMedia("(max-width: 768px)");
    setIsMobile(mq.matches);
    const handler = (e: MediaQueryListEvent) => setIsMobile(e.matches);
    mq.addEventListener("change", handler);
    return () => mq.removeEventListener("change", handler);
  }, []);

  // Ref callback — sets muted BEFORE browser evaluates autoplay policy.
  // Same pattern as FullScaleCreates.tsx for iOS/Safari autoplay reliability.
  const videoRefCallback = useCallback((node: HTMLVideoElement | null) => {
    videoRef.current = node;
    if (!node) return;
    node.muted = true;
    node.setAttribute("muted", "");
    node.setAttribute("playsinline", "");
    node.setAttribute("webkit-playsinline", "");
    node.defaultMuted = true;
    node.play().catch(() => {});
  }, []);

  // Retry playback on first touch or when video data arrives
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    const tryPlay = () => {
      video.muted = true;
      video.play().catch(() => {});
    };
    video.addEventListener("loadeddata", tryPlay);
    window.addEventListener("touchstart", tryPlay, { once: true });
    return () => {
      video.removeEventListener("loadeddata", tryPlay);
    };
  }, []);

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b bg-card/80 backdrop-blur-md sticky top-0 z-30">
        <div className="max-w-6xl mx-auto px-6 py-3 flex items-center justify-between">
          <a href="/" data-testid="link-brands-logo">
            <img src={logoUrl} alt="FullScale" className="h-7" />
          </a>
          <div className="flex items-center gap-3">
            <Badge
              variant="outline"
              className="text-xs font-medium border-emerald-400/40 text-emerald-300 bg-emerald-400/5"
            >
              <Briefcase className="w-3 h-3 mr-1" />
              For Brands
            </Badge>
            <a href="/auth?mode=signup&userType=brand" data-testid="link-brands-header-signup">
              <Button size="sm" className="gap-1.5 bg-emerald-500 hover:bg-emerald-500/90 text-white">
                Sign Up Now
                <ArrowRight className="w-3.5 h-3.5" />
              </Button>
            </a>
          </div>
        </div>
      </header>

      {/* Hero Section — video background with gradient overlay */}
      <section className="relative min-h-[520px] md:min-h-[640px] overflow-hidden">
        {heroVideoUrl && !videoFailed ? (
          <video
            ref={videoRefCallback}
            key={isMobile ? "mobile" : "desktop"}
            src={isMobile ? heroVideoMobileUrl : heroVideoUrl}
            preload="auto"
            autoPlay
            loop
            muted
            playsInline
            className="absolute inset-0 w-full h-full object-cover"
            onError={() => setVideoFailed(true)}
            data-testid="video-brands-hero"
          />
        ) : null}
        <div className="absolute inset-0 bg-gradient-to-b from-black/70 via-black/55 to-background" />
        <div className="absolute inset-0 bg-gradient-to-br from-emerald-500/10 via-transparent to-black/30" />

        <div className="relative z-10 max-w-6xl mx-auto px-6 pt-24 pb-20">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
            className="text-center max-w-3xl mx-auto"
          >
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-emerald-400/10 border border-emerald-400/30 text-emerald-300 text-sm font-medium mb-6 backdrop-blur-sm">
              <Briefcase className="w-4 h-4" />
              FullScale For Brands
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight mb-6 text-white">
              Your brand,{" "}
              <span className="bg-gradient-to-r from-emerald-300 via-emerald-400 to-emerald-300 bg-clip-text text-transparent">
                in content that's already performing.
              </span>
            </h1>
            <p className="text-lg md:text-xl text-white/80 leading-relaxed max-w-2xl mx-auto mb-8">
              Drop your product into podcast desks, DJ booths, gaming setups, and creator studios — without the heavy friction of finding talent, negotiating rates, or chasing reshoots. Test creator-product associations before you commit the big budget.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <a href="/auth?mode=signup&userType=brand" data-testid="link-brands-hero-signup">
                <Button
                  size="lg"
                  className="gap-2 bg-emerald-500 hover:bg-emerald-500/90 text-white shadow-2xl shadow-emerald-500/20"
                >
                  Sign Up Now
                  <ArrowRight className="w-4 h-4" />
                </Button>
              </a>
              <Button
                size="lg"
                variant="outline"
                className="gap-2 border-white/30 text-white hover:bg-white/10"
                onClick={() => {
                  document.getElementById("how-it-works")?.scrollIntoView({ behavior: "smooth" });
                }}
                data-testid="button-brands-how-it-works"
              >
                <Play className="w-4 h-4" />
                See How It Works
              </Button>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Section 2 — Friction comparison */}
      <section id="how-it-works" className="max-w-6xl mx-auto px-6 py-20 scroll-mt-20">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center mb-12 max-w-3xl mx-auto"
        >
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4 tracking-tight">
            There are two ways to get your product in front of audiences.
          </h2>
          <p className="text-lg text-muted-foreground leading-relaxed">
            One way is expensive, slow, and hit-or-miss. The other is FullScale.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 gap-6">
          {/* Traditional path card */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1, duration: 0.5 }}
          >
            <Card className="h-full border-red-500/20 bg-red-950/10">
              <CardContent className="p-8">
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-10 h-10 rounded-lg bg-red-500/10 border border-red-500/30 flex items-center justify-center">
                    <XCircle className="w-5 h-5 text-red-400" />
                  </div>
                  <div>
                    <div className="text-xs uppercase tracking-widest text-red-400/80 font-semibold">
                      The Traditional Path
                    </div>
                    <div className="text-lg font-bold text-foreground">Heavy friction, hit-or-miss outcomes</div>
                  </div>
                </div>
                <ul className="space-y-4">
                  {FRICTION_TRADITIONAL.map((item) => {
                    const Icon = item.icon;
                    return (
                      <li key={item.text} className="flex items-start gap-3">
                        <div className="w-8 h-8 rounded-md bg-red-500/5 border border-red-500/20 flex items-center justify-center flex-shrink-0 mt-0.5">
                          <Icon className="w-4 h-4 text-red-400/80" />
                        </div>
                        <p className="text-sm md:text-base text-foreground/90 leading-relaxed">{item.text}</p>
                      </li>
                    );
                  })}
                </ul>
                <div className="mt-8 pt-6 border-t border-red-500/10">
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    Average timeline: <span className="text-red-400/90 font-semibold">6–12 weeks</span>
                    <span className="mx-2 text-muted-foreground/50">·</span>
                    Average cost: <span className="text-red-400/90 font-semibold">$50K+</span>
                    <span className="mx-2 text-muted-foreground/50">·</span>
                    Outcome: <span className="text-red-400/90 font-semibold">hit or miss</span>
                  </p>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          {/* FullScale path card */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.2, duration: 0.5 }}
          >
            <Card className="h-full border-emerald-400/30 bg-emerald-950/10 shadow-lg shadow-emerald-500/5">
              <CardContent className="p-8">
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-10 h-10 rounded-lg bg-emerald-400/10 border border-emerald-400/40 flex items-center justify-center">
                    <CheckCircle2 className="w-5 h-5 text-emerald-300" />
                  </div>
                  <div>
                    <div className="text-xs uppercase tracking-widest text-emerald-300 font-semibold">
                      With FullScale
                    </div>
                    <div className="text-lg font-bold text-foreground">Proven content, measurable outcomes</div>
                  </div>
                </div>
                <ul className="space-y-4">
                  {FRICTION_FULLSCALE.map((item) => {
                    const Icon = item.icon;
                    return (
                      <li key={item.text} className="flex items-start gap-3">
                        <div className="w-8 h-8 rounded-md bg-emerald-400/10 border border-emerald-400/30 flex items-center justify-center flex-shrink-0 mt-0.5">
                          <Icon className="w-4 h-4 text-emerald-300" />
                        </div>
                        <p className="text-sm md:text-base text-foreground/90 leading-relaxed">{item.text}</p>
                      </li>
                    );
                  })}
                </ul>
                <div className="mt-8 pt-6 border-t border-emerald-400/20">
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    Average timeline: <span className="text-emerald-300 font-semibold">48 hours</span>
                    <span className="mx-2 text-muted-foreground/50">·</span>
                    Average cost: <span className="text-emerald-300 font-semibold">a fraction</span>
                    <span className="mx-2 text-muted-foreground/50">·</span>
                    Outcome: <span className="text-emerald-300 font-semibold">measurable</span>
                  </p>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        </div>
      </section>

      {/* Brand Partner Strip — marquee of brands using FullScale */}
      <section className="py-10 md:py-16 overflow-hidden border-y bg-card/30">
        <p className="text-[10px] md:text-xs uppercase tracking-widest text-muted-foreground/60 mb-6 md:mb-8 font-medium text-center">
          Trusted by leading brands
        </p>
        <div className="relative w-full overflow-hidden">
          <div className="flex w-max animate-brand-marquee hover:[animation-play-state:paused]">
            {[...Array(4)].map((_, setIndex) => (
              <div key={setIndex} className="flex items-center shrink-0" style={{ gap: "4rem" }}>
                {BRAND_PARTNERS.map((brand) => (
                  <div
                    key={`${setIndex}-${brand.slug}`}
                    className="px-5 py-3 md:px-6 md:py-4 rounded-xl backdrop-blur-md bg-white/95 border border-white/10 hover:bg-white hover:scale-105 hover:shadow-lg hover:shadow-emerald-500/5 transition-all duration-300 ml-16 first:ml-16 flex items-center justify-center"
                    style={{ minWidth: "160px", height: "72px" }}
                  >
                    <img
                      src={`/brand-logos/${brand.slug}.png`}
                      alt={brand.name}
                      loading="lazy"
                      className="max-h-10 md:max-h-12 w-auto object-contain"
                      onError={(e) => {
                        // Graceful fallback: if PNG isn't saved yet, show brand name as styled text
                        const img = e.currentTarget;
                        const fallback = document.createElement("span");
                        fallback.className = "text-sm md:text-base font-bold tracking-tight text-slate-900";
                        fallback.textContent = brand.name;
                        img.replaceWith(fallback);
                      }}
                      data-testid={`img-brand-${brand.slug}`}
                    />
                  </div>
                ))}
              </div>
            ))}
          </div>
        </div>
        <style>{`
          @keyframes brand-marquee {
            0% { transform: translateX(0); }
            100% { transform: translateX(-25%); }
          }
          .animate-brand-marquee {
            animation: brand-marquee 30s linear infinite;
          }
        `}</style>
      </section>

      {/* Section 3 — "See it in action" — 3-scene Reality-vs-Augmented slider showcase */}
      <section className="relative overflow-hidden py-20">
        {/* Ambient backdrop blurs */}
        <div className="absolute top-0 left-0 w-[500px] h-[500px] bg-emerald-500/10 rounded-full blur-[200px] pointer-events-none" />
        <div className="absolute bottom-0 right-0 w-[500px] h-[500px] bg-emerald-400/10 rounded-full blur-[200px] pointer-events-none" />

        <div className="relative max-w-5xl mx-auto px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12 max-w-3xl mx-auto"
          >
            <Badge
              variant="outline"
              className="mb-5 text-xs font-medium border-emerald-400/40 text-emerald-300 bg-emerald-400/5"
            >
              <Sparkles className="w-3 h-3 mr-1" />
              See It In Action
            </Badge>
            <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4 tracking-tight">
              Real products. Real creator moments.
            </h2>
            <p className="text-lg text-muted-foreground leading-relaxed">
              Drag the slider on each scene to see what FullScale's AI does to a creator's existing content — no reshoots, no prop-swapping, no production day required.
            </p>
          </motion.div>

          <div className="space-y-16">
            {SHOWCASE_SCENES.map((scene, idx) => (
              <motion.div
                key={scene.testId}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-100px" }}
                transition={{ delay: idx * 0.15, duration: 0.6 }}
                className="space-y-5"
              >
                <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-2">
                  <div>
                    <div className="text-xs uppercase tracking-widest text-emerald-300/80 font-semibold mb-1">
                      {scene.sceneNumber}
                    </div>
                    <h3 className="text-xl md:text-2xl font-bold text-foreground tracking-tight">
                      {scene.label}
                    </h3>
                  </div>
                  <Badge
                    variant="outline"
                    className="text-xs font-medium border-white/15 text-white/70 bg-white/5 self-start sm:self-auto"
                  >
                    <Layers className="w-3 h-3 mr-1" />
                    Drag to Compare
                  </Badge>
                </div>

                <SceneComparisonSlider
                  realityImg={scene.reality}
                  augmentedImg={scene.augmented}
                  realityAlt={scene.realityAlt}
                  augmentedAlt={scene.augmentedAlt}
                  testIdPrefix={scene.testId}
                />

                <p className="text-sm md:text-base text-muted-foreground leading-relaxed max-w-3xl">
                  {scene.description}
                </p>
              </motion.div>
            ))}
          </div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mt-16 max-w-2xl mx-auto"
          >
            <p className="text-sm text-muted-foreground/70">
              Want to see your product in your creator's content? Upload a PNG when you sign up — we'll generate previews for you before you commit anything.
            </p>
          </motion.div>
        </div>
      </section>

      {/* Section 4 — Capabilities */}
      <section className="border-y bg-card/30">
        <div className="max-w-6xl mx-auto px-6 py-20">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12 max-w-3xl mx-auto"
          >
            <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4 tracking-tight">
              Stickers. Products. Screens. All of it.
            </h2>
            <p className="text-lg text-muted-foreground leading-relaxed">
              If it has a flat surface, a screen, or an empty frame — you can own the moment.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {CAPABILITIES.map((cap, idx) => {
              const Icon = cap.icon;
              return (
                <motion.div
                  key={cap.title}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: idx * 0.1, duration: 0.4 }}
                >
                  <Card className="h-full border-emerald-400/10 hover:border-emerald-400/30 transition-all duration-300">
                    <CardContent className="p-6">
                      <div className="w-12 h-12 rounded-xl bg-emerald-400/10 border border-emerald-400/30 flex items-center justify-center mb-4">
                        <Icon className="w-6 h-6 text-emerald-300" />
                      </div>
                      <h3 className="font-semibold text-foreground mb-2 text-base md:text-lg">{cap.title}</h3>
                      <p className="text-sm text-muted-foreground leading-relaxed">{cap.description}</p>
                    </CardContent>
                  </Card>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Section 5 — "How a placement happens" — 4-step process narrative */}
      <section className="max-w-6xl mx-auto px-6 py-20">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center mb-14 max-w-3xl mx-auto"
        >
          <Badge
            variant="outline"
            className="mb-5 text-xs font-medium border-emerald-400/40 text-emerald-300 bg-emerald-400/5"
          >
            <Target className="w-3 h-3 mr-1" />
            The Placement Flow
          </Badge>
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4 tracking-tight">
            From product upload to live placement in four steps.
          </h2>
          <p className="text-lg text-muted-foreground leading-relaxed">
            No production crew. No reshoots. No waiting months for a creator to decide.
          </p>
        </motion.div>

        {/* Step grid with connecting line on desktop */}
        <div className="relative">
          {/* Desktop-only connecting line */}
          <div className="hidden md:block absolute top-14 left-[12.5%] right-[12.5%] h-px bg-gradient-to-r from-transparent via-emerald-400/30 to-transparent pointer-events-none" />

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 relative">
            {PLACEMENT_STEPS.map((step, idx) => {
              const Icon = step.icon;
              return (
                <motion.div
                  key={step.step}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: idx * 0.1, duration: 0.5 }}
                >
                  <Card className="h-full border-emerald-400/10 hover:border-emerald-400/30 transition-all duration-300 bg-card/40 backdrop-blur-sm">
                    <CardContent className="p-6">
                      {/* Big numbered circle */}
                      <div className="relative inline-flex items-center justify-center w-14 h-14 rounded-full bg-background border-2 border-emerald-400/40 mb-5">
                        <Icon className="w-6 h-6 text-emerald-300" />
                        <div className="absolute -top-1 -right-1 w-6 h-6 rounded-full bg-emerald-500 border-2 border-background flex items-center justify-center text-[11px] font-bold text-white">
                          {idx + 1}
                        </div>
                      </div>
                      <div className="text-xs uppercase tracking-widest text-emerald-300/80 font-semibold mb-2">
                        {step.step}
                      </div>
                      <h3 className="font-semibold text-foreground mb-3 text-lg leading-tight">
                        {step.title}
                      </h3>
                      <p className="text-sm text-muted-foreground leading-relaxed">
                        {step.description}
                      </p>
                    </CardContent>
                  </Card>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Section 6 — Test-and-learn */}
      <section className="max-w-6xl mx-auto px-6 py-20">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center mb-12 max-w-3xl mx-auto"
        >
          <Badge
            variant="outline"
            className="mb-5 text-xs font-medium border-emerald-400/40 text-emerald-300 bg-emerald-400/5"
          >
            <FlaskConical className="w-3 h-3 mr-1" />
            Test & Learn
          </Badge>
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4 tracking-tight">
            Test everything before you scale anything.
          </h2>
          <p className="text-lg text-muted-foreground leading-relaxed">
            Figure out what lands — and with whom — before you commit real budget.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {TEST_AND_LEARN.map((feature, idx) => {
            const Icon = feature.icon;
            return (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: idx * 0.12, duration: 0.5 }}
              >
                <Card className="h-full border-emerald-400/10 hover:border-emerald-400/30 transition-all duration-300">
                  <CardContent className="p-7">
                    <div className="flex items-center gap-3 mb-4">
                      <div className="w-10 h-10 rounded-lg bg-emerald-400/10 border border-emerald-400/30 flex items-center justify-center">
                        <Icon className="w-5 h-5 text-emerald-300" />
                      </div>
                      <div className="text-xs uppercase tracking-widest text-emerald-300/80 font-semibold">
                        Step {idx + 1}
                      </div>
                    </div>
                    <h3 className="font-semibold text-foreground mb-3 text-lg">{feature.title}</h3>
                    <p className="text-sm text-muted-foreground leading-relaxed">{feature.description}</p>
                  </CardContent>
                </Card>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* Section 5 — Final sign-up CTA */}
      <section className="relative overflow-hidden">
        {/* Accent gradient backdrop */}
        <div className="absolute inset-0 bg-gradient-to-br from-emerald-500/15 via-background to-emerald-400/5" />
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_rgba(16,185,129,0.12)_0%,_transparent_60%)]" />

        <div className="relative z-10 max-w-4xl mx-auto px-6 py-24 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <div className="inline-flex items-center justify-center w-14 h-14 rounded-2xl bg-emerald-400/15 border border-emerald-400/40 mb-6">
              <Briefcase className="w-7 h-7 text-emerald-300" />
            </div>
            <h2 className="text-3xl md:text-5xl font-bold tracking-tight text-foreground mb-5">
              Ready to put your brand in content that's{" "}
              <span className="bg-gradient-to-r from-emerald-300 via-emerald-400 to-emerald-300 bg-clip-text text-transparent">
                already winning?
              </span>
            </h2>
            <p className="text-lg md:text-xl text-muted-foreground leading-relaxed max-w-2xl mx-auto mb-10">
              Sign up and our team walks you through a brief tailored to your brand, budget, and audience. Pick a creator, test a placement, see the numbers — before you commit.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <a href="/auth?mode=signup&userType=brand" data-testid="link-brands-final-signup">
                <Button
                  size="lg"
                  className="gap-2 bg-emerald-500 hover:bg-emerald-500/90 text-white shadow-2xl shadow-emerald-500/25 px-8"
                >
                  Sign Up Now
                  <ArrowRight className="w-4 h-4" />
                </Button>
              </a>
              <a
                href="mailto:hello@gofullscale.co?subject=Brand%20Interest%20%E2%80%94%20FullScale"
                data-testid="link-brands-final-talk"
              >
                <Button
                  size="lg"
                  variant="outline"
                  className="gap-2 border-emerald-400/40 text-emerald-300 hover:bg-emerald-400/10"
                >
                  <Mail className="w-4 h-4" />
                  Talk to Our Team
                </Button>
              </a>
            </div>
            <p className="text-xs text-muted-foreground/70 mt-8">
              No upfront commitment. Pick a creator, test a placement, see the numbers.
            </p>
          </motion.div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
