import { useState, useRef, useEffect, useCallback } from "react";
import { motion } from "framer-motion";
import { Briefcase, ArrowLeft, ArrowRight, Mail } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import logoUrl from "@assets/fullscale-logo_1767679525676.png";

import heroVideoUrl from "@assets/brands_hero_loop.mp4";
import heroVideoMobileUrl from "@assets/brands_hero_loop_mobile.mp4";

/**
 * FullScale For Brands landing page.
 *
 * Currently a hero-only placeholder — the full page (friction-vs-FullScale
 * contrast section, capabilities, test-and-learn pitch, brand-specific
 * signup CTA routing to the brand onboarding brief) ships in the next
 * phase of marketing work.
 *
 * Hero video: `attached_assets/brands_hero_loop.mp4` (+ `_mobile.mp4`).
 * The current file is a temporary placeholder sourced from the existing
 * cinematic inventory. A purpose-built brands montage (DJ booth / podcast
 * desk / gamer setup / product placement) will be generated by Replit
 * Agent and will drop into the same paths — no code changes needed when
 * that happens, the Vite @assets import will pick up the new file.
 *
 * Hero pattern mirrors FullScaleCreates.tsx exactly:
 *   - Vite @assets imports for desktop + mobile video variants
 *   - Ref callback that forces muted/playsInline before browser evaluates autoplay
 *   - videoFailed state → falls back to gradient-only hero if the video errors
 *   - Mobile/desktop variant switching via window.matchMedia
 *   - Dark gradient overlay always present for text readability
 */
export default function Brands() {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const [videoFailed, setVideoFailed] = useState(false);
  const [isMobile, setIsMobile] = useState(() =>
    typeof window !== "undefined" && window.matchMedia("(max-width: 768px)").matches
  );

  useEffect(() => {
    const mq = window.matchMedia("(max-width: 768px)");
    setIsMobile(mq.matches);
    const handler = (e: MediaQueryListEvent) => setIsMobile(e.matches);
    mq.addEventListener("change", handler);
    return () => mq.removeEventListener("change", handler);
  }, []);

  // Ref callback — sets muted BEFORE browser evaluates autoplay policy.
  // This is the iOS/Safari-friendly pattern used in FullScaleCreates.tsx and Landing.tsx.
  const videoRefCallback = useCallback((node: HTMLVideoElement | null) => {
    videoRef.current = node;
    if (!node) return;
    node.muted = true;
    node.setAttribute("muted", "");
    node.setAttribute("playsinline", "");
    node.setAttribute("webkit-playsinline", "");
    node.defaultMuted = true;
    node.play().catch(() => {});
  }, []);

  // Retry playback on first touch or when video data arrives
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    const tryPlay = () => {
      video.muted = true;
      video.play().catch(() => {});
    };
    video.addEventListener("loadeddata", tryPlay);
    window.addEventListener("touchstart", tryPlay, { once: true });
    return () => {
      video.removeEventListener("loadeddata", tryPlay);
    };
  }, []);

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b bg-card/80 backdrop-blur-md sticky top-0 z-30">
        <div className="max-w-6xl mx-auto px-6 py-3 flex items-center justify-between">
          <a href="/">
            <img src={logoUrl} alt="FullScale" className="h-7" data-testid="link-brands-logo" />
          </a>
          <Badge variant="outline" className="text-xs font-medium border-emerald-400/40 text-emerald-300 bg-emerald-400/5">
            <Briefcase className="w-3 h-3 mr-1" />
            For Brands
          </Badge>
        </div>
      </header>

      {/* Hero Section — video background with gradient overlay */}
      <section className="relative min-h-[520px] md:min-h-[640px] overflow-hidden">
        {/* Video background (falls back to gradient if video not available) */}
        {heroVideoUrl && !videoFailed ? (
          <video
            ref={videoRefCallback}
            key={isMobile ? "mobile" : "desktop"}
            src={isMobile ? heroVideoMobileUrl : heroVideoUrl}
            preload="auto"
            autoPlay
            loop
            muted
            playsInline
            className="absolute inset-0 w-full h-full object-cover"
            onError={() => setVideoFailed(true)}
            data-testid="video-brands-hero"
          />
        ) : null}
        {/* Dark gradient overlay — always present for text readability */}
        <div className="absolute inset-0 bg-gradient-to-b from-black/70 via-black/55 to-background" />
        {/* Emerald accent gradient to match the For Brands visual language */}
        <div className="absolute inset-0 bg-gradient-to-br from-emerald-500/10 via-transparent to-black/30" />

        <div className="relative z-10 max-w-6xl mx-auto px-6 pt-24 pb-20">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
            className="text-center max-w-3xl mx-auto"
          >
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-emerald-400/10 border border-emerald-400/30 text-emerald-300 text-sm font-medium mb-6 backdrop-blur-sm">
              <Briefcase className="w-4 h-4" />
              FullScale For Brands
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight mb-6 text-white">
              Your brand,{" "}
              <span className="bg-gradient-to-r from-emerald-300 via-emerald-400 to-emerald-300 bg-clip-text text-transparent">
                in content that's already performing.
              </span>
            </h1>
            <p className="text-lg md:text-xl text-white/80 leading-relaxed max-w-2xl mx-auto mb-8">
              Drop your product into podcast desks, DJ booths, gaming setups, and creator studios — without the heavy friction of finding talent, negotiating rates, or chasing reshoots. Test creator-product associations before you commit the big budget.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <a
                href="mailto:hello@gofullscale.co?subject=Brand%20Interest%20%E2%80%94%20FullScale"
                data-testid="link-brands-contact"
              >
                <Button size="lg" className="gap-2 bg-emerald-500 hover:bg-emerald-500/90 text-white shadow-2xl shadow-emerald-500/20">
                  Get in Touch
                  <Mail className="w-4 h-4" />
                </Button>
              </a>
              <a href="/" data-testid="link-brands-home">
                <Button
                  size="lg"
                  variant="outline"
                  className="gap-2 border-white/30 text-white hover:bg-white/10"
                >
                  <ArrowLeft className="w-4 h-4" />
                  Back to Home
                </Button>
              </a>
            </div>
          </motion.div>
        </div>
      </section>

      {/* "Coming soon" placeholder section — replaced in next phase with the
          real brands page content (friction section, capabilities, test-and-
          learn pitch, brand signup CTA). */}
      <section className="max-w-4xl mx-auto px-6 py-16 text-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-emerald-400/10 border border-emerald-400/30 mb-6">
            <Briefcase className="w-8 h-8 text-emerald-300" />
          </div>
          <h2 className="text-2xl md:text-3xl font-bold text-foreground mb-4">
            A dedicated Brands experience is launching shortly.
          </h2>
          <p className="text-muted-foreground leading-relaxed max-w-2xl mx-auto mb-8">
            We're building the full walkthrough — how placement works, what surfaces are available, how the test-and-learn flow unfolds, and a brand-specific sign-up brief. In the meantime, reach out to our team and we'll walk you through it directly.
          </p>
          <a href="mailto:hello@gofullscale.co?subject=Brand%20Interest%20%E2%80%94%20FullScale">
            <Button size="lg" className="gap-2 bg-emerald-500 hover:bg-emerald-500/90 text-white">
              Talk to Our Team
              <ArrowRight className="w-4 h-4" />
            </Button>
          </a>
        </motion.div>
      </section>
    </div>
  );
}
