import { useState, useRef, useEffect, useCallback } from "react";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";
import { useMemo } from "react";
import { useContent } from "@/content";
import { motion } from "framer-motion";
import {
  Briefcase,
  ArrowRight,
  Mail,
  Play,
  Clock,
  DollarSign,
  Film,
  TrendingDown,
  Sparkles,
  Target,
  TrendingUp,
  Package,
  Tag,
  Monitor,
  Layers,
  FlaskConical,
  CheckCircle2,
  XCircle,
  Gauge,
  Upload,
  ScanSearch,
  BarChart3,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Footer } from "@/components/Footer";
import { SceneComparisonSlider } from "@/components/SceneComparisonSlider";
import logoUrl from "@assets/fullscale-logo_1767679525676.png";

import heroVideoUrl from "@assets/brands_hero_loop.mp4";
import heroVideoMobileUrl from "@assets/brands_hero_loop_mobile.mp4";

// Scene pairs for the "See it in action" showcase — three purpose-built
// "clean augmentation" pairs generated specifically for /brands. Each pair
// is the same scene with ONLY a product and its shadow added in the
// augmented version, matching the quality bar set by the Landing page's
// kitchen/Boxed Water pair. Generated by Replit Agent in commit d43626b.
import sceneKitchenReality from "@assets/generated_images/brands_kitchen_reality.png";
import sceneKitchenAugmented from "@assets/generated_images/brands_kitchen_augmented.png";
import sceneDjReality from "@assets/generated_images/brands_dj_reality.png";
import sceneDjAugmented from "@assets/generated_images/brands_dj_augmented.png";
import sceneGamerReality from "@assets/generated_images/brands_gamer_reality.png";
import sceneGamerAugmented from "@assets/generated_images/brands_gamer_augmented.png";

/**
 * FullScale For Brands landing page.
 *
 * Full-page brand-facing marketing site. Five beats:
 *   1. Hero — 4-scene video loop (podcast / DJ / gaming / kitchen) with
 *      hero copy and dual CTAs ("Sign Up Now" + "See How It Works")
 *   2. Friction comparison — traditional brand-talent path vs FullScale path,
 *      side-by-side cards
 *   3. Capabilities — four placement types (physical product / stickers /
 *      on-screen overlays / ambient branding)
 *   4. Test-and-learn — three-card row explaining pre-commit validation
 *      (match → A/B → measure-and-scale)
 *   5. Sign-up CTA — final push to the brand signup flow
 *
 * Hero video pattern mirrors FullScaleCreates.tsx exactly (Vite @assets
 * imports for desktop + mobile variants, ref callback for iOS autoplay,
 * videoFailed fallback, window.matchMedia breakpoint switching).
 */

// (BRAND_PARTNERS marquee removed — landing page now carries the single
// canonical logo cloud at Landing.tsx > partnerLogos. Brand logos for
// JUST Water / Naturade / Shinju / VeganSmart / SETO remain available at
// client/public/brand-logos/{slug}.png if a future section needs them.)

/* The WORDS live in client/src/content/brands.{en,ar}.ts. What stays here is
   everything a translator must not be able to touch: the icon components, the
   scene images and the data-testids. They are zipped to the copy by index
   inside the component, so the JSX below is unchanged and a reordered Arabic
   list can never drag an icon or a testId out of place with it. */
const FRICTION_TRADITIONAL_ICONS = [Clock, DollarSign, Film, TrendingDown];
const FRICTION_FULLSCALE_ICONS = [Sparkles, Target, FlaskConical, TrendingUp];
const CAPABILITY_ICONS = [Package, Tag, Monitor, Layers];
const PLACEMENT_STEP_ICONS = [Upload, ScanSearch, CheckCircle2, BarChart3];
const TEST_AND_LEARN_ICONS = [Target, FlaskConical, Gauge];
const SHOWCASE_MEDIA = [
  { reality: sceneKitchenReality, augmented: sceneKitchenAugmented, testId: "showcase-kitchen" },
  { reality: sceneDjReality, augmented: sceneDjAugmented, testId: "showcase-dj" },
  { reality: sceneGamerReality, augmented: sceneGamerAugmented, testId: "showcase-gamer" },
];

export default function Brands() {
  const c = useContent("brands");

  /* Same shapes the JSX below already expects — copy from the locale module,
     icons and media from the lists above, zipped by index. */
  const FRICTION_TRADITIONAL = useMemo(
    () => c.friction.traditional.map((text, i) => ({ icon: FRICTION_TRADITIONAL_ICONS[i], text })),
    [c],
  );
  const FRICTION_FULLSCALE = useMemo(
    () => c.friction.fullscale.map((text, i) => ({ icon: FRICTION_FULLSCALE_ICONS[i], text })),
    [c],
  );
  const CAPABILITIES = useMemo(
    () => c.capabilities.items.map((it, i) => ({ ...it, icon: CAPABILITY_ICONS[i] })),
    [c],
  );
  const PLACEMENT_STEPS = useMemo(
    () => c.steps.items.map((it, i) => ({ ...it, icon: PLACEMENT_STEP_ICONS[i] })),
    [c],
  );
  const TEST_AND_LEARN = useMemo(
    () => c.testLearn.items.map((it, i) => ({ ...it, icon: TEST_AND_LEARN_ICONS[i] })),
    [c],
  );
  const SHOWCASE_SCENES = useMemo(
    () => c.showcase.scenes.map((sc, i) => ({ ...sc, ...SHOWCASE_MEDIA[i] })),
    [c],
  );

  const videoRef = useRef<HTMLVideoElement | null>(null);
  const [videoFailed, setVideoFailed] = useState(false);
  const [isMobile, setIsMobile] = useState(() =>
    typeof window !== "undefined" && window.matchMedia("(max-width: 768px)").matches
  );

  useEffect(() => {
    const mq = window.matchMedia("(max-width: 768px)");
    setIsMobile(mq.matches);
    const handler = (e: MediaQueryListEvent) => setIsMobile(e.matches);
    mq.addEventListener("change", handler);
    return () => mq.removeEventListener("change", handler);
  }, []);

  // Ref callback — sets muted BEFORE browser evaluates autoplay policy.
  // Same pattern as FullScaleCreates.tsx for iOS/Safari autoplay reliability.
  const videoRefCallback = useCallback((node: HTMLVideoElement | null) => {
    videoRef.current = node;
    if (!node) return;
    node.muted = true;
    node.setAttribute("muted", "");
    node.setAttribute("playsinline", "");
    node.setAttribute("webkit-playsinline", "");
    node.defaultMuted = true;
    node.play().catch(() => {});
  }, []);

  // Retry playback on first touch or when video data arrives
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    const tryPlay = () => {
      video.muted = true;
      video.play().catch(() => {});
    };
    video.addEventListener("loadeddata", tryPlay);
    window.addEventListener("touchstart", tryPlay, { once: true });
    return () => {
      video.removeEventListener("loadeddata", tryPlay);
    };
  }, []);

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b bg-card/80 backdrop-blur-md sticky top-0 z-30">
        <div className="max-w-6xl mx-auto px-6 py-3 flex items-center justify-between">
          <a href="/" data-testid="link-brands-logo">
            <img src={logoUrl} alt="FullScale" className="h-7" />
          </a>
          <div className="flex items-center gap-3">
            <LanguageSwitcher />
            <Badge
              variant="outline"
              className="text-xs font-medium border-emerald-400/40 text-emerald-300 bg-emerald-400/5"
            >
              <Briefcase className="w-3 h-3 mr-1" />
              For Brands
            </Badge>
            <a
              href="https://airtable.com/app9YlRgIcR9M29p6/pag6tzECkzzXYQoti/form"
              target="_blank"
              rel="noopener noreferrer"
              data-testid="link-brands-header-signup"
            >
              <Button size="sm" className="gap-1.5 bg-emerald-500 hover:bg-emerald-500/90 text-white">
                Apply for Access
                <ArrowRight className="w-3.5 h-3.5" />
              </Button>
            </a>
          </div>
        </div>
      </header>

      {/* Hero Section — video background with gradient overlay */}
      <section className="relative min-h-[520px] md:min-h-[640px] overflow-hidden">
        {heroVideoUrl && !videoFailed ? (
          <video
            ref={videoRefCallback}
            key={isMobile ? "mobile" : "desktop"}
            src={isMobile ? heroVideoMobileUrl : heroVideoUrl}
            preload="auto"
            autoPlay
            loop
            muted
            playsInline
            className="absolute inset-0 w-full h-full object-cover"
            onError={() => setVideoFailed(true)}
            data-testid="video-brands-hero"
          />
        ) : null}
        <div className="absolute inset-0 bg-gradient-to-b from-black/70 via-black/55 to-background" />
        <div className="absolute inset-0 bg-gradient-to-br from-emerald-500/10 via-transparent to-black/30" />

        <div className="relative z-10 max-w-6xl mx-auto px-6 pt-24 pb-20">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
            className="text-center max-w-3xl mx-auto"
          >
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-emerald-400/10 border border-emerald-400/30 text-emerald-300 text-sm font-medium mb-6 backdrop-blur-sm">
              <Briefcase className="w-4 h-4" />
              FullScale For Brands
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight mb-6 text-white">
              Your brand,{" "}
              <span className="bg-gradient-to-r from-emerald-300 via-emerald-400 to-emerald-300 bg-clip-text text-transparent">
                in content that's already performing.
              </span>
            </h1>
            <p className="text-lg md:text-xl text-white/80 leading-relaxed max-w-2xl mx-auto mb-8">
              {c.hero.deck}
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <a
                href="https://airtable.com/app9YlRgIcR9M29p6/pag6tzECkzzXYQoti/form"
                target="_blank"
                rel="noopener noreferrer"
                data-testid="link-brands-hero-signup"
              >
                <Button
                  size="lg"
                  className="gap-2 bg-emerald-500 hover:bg-emerald-500/90 text-white shadow-2xl shadow-emerald-500/20"
                >
                  Apply for Access
                  <ArrowRight className="w-4 h-4" />
                </Button>
              </a>
              <Button
                size="lg"
                variant="outline"
                className="gap-2 border-white/30 text-white hover:bg-white/10"
                onClick={() => {
                  document.getElementById("how-it-works")?.scrollIntoView({ behavior: "smooth" });
                }}
                data-testid="button-brands-how-it-works"
              >
                <Play className="w-4 h-4" />
                See How It Works
              </Button>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Section 2 — Friction comparison */}
      <section id="how-it-works" className="max-w-6xl mx-auto px-6 py-20 scroll-mt-20">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center mb-12 max-w-3xl mx-auto"
        >
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4 tracking-tight">
            {c.friction.title}
          </h2>
          <p className="text-lg text-muted-foreground leading-relaxed">
            {c.friction.deck}
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 gap-6">
          {/* Traditional path card */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1, duration: 0.5 }}
          >
            <Card className="h-full border-red-500/20 bg-red-950/10">
              <CardContent className="p-8">
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-10 h-10 rounded-lg bg-red-500/10 border border-red-500/30 flex items-center justify-center">
                    <XCircle className="w-5 h-5 text-red-400" />
                  </div>
                  <div>
                    <div className="text-xs uppercase tracking-widest text-red-400/80 font-semibold">
                      The Traditional Path
                    </div>
                    <div className="text-lg font-bold text-foreground">{c.friction.traditionalLabel}</div>
                  </div>
                </div>
                <ul className="space-y-4">
                  {FRICTION_TRADITIONAL.map((item) => {
                    const Icon = item.icon;
                    return (
                      <li key={item.text} className="flex items-start gap-3">
                        <div className="w-8 h-8 rounded-md bg-red-500/5 border border-red-500/20 flex items-center justify-center flex-shrink-0 mt-0.5">
                          <Icon className="w-4 h-4 text-red-400/80" />
                        </div>
                        <p className="text-sm md:text-base text-foreground/90 leading-relaxed">{item.text}</p>
                      </li>
                    );
                  })}
                </ul>
                <div className="mt-8 pt-6 border-t border-red-500/10">
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    Average timeline: <span className="text-red-400/90 font-semibold">{c.friction.statSlow}</span>
                    <span className="mx-2 text-muted-foreground/50">·</span>
                    Average cost: <span className="text-red-400/90 font-semibold">$50K+</span>
                    <span className="mx-2 text-muted-foreground/50">·</span>
                    Outcome: <span className="text-red-400/90 font-semibold">{c.friction.statUncertain}</span>
                  </p>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          {/* FullScale path card */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.2, duration: 0.5 }}
          >
            <Card className="h-full border-emerald-400/30 bg-emerald-950/10 shadow-lg shadow-emerald-500/5">
              <CardContent className="p-8">
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-10 h-10 rounded-lg bg-emerald-400/10 border border-emerald-400/40 flex items-center justify-center">
                    <CheckCircle2 className="w-5 h-5 text-emerald-300" />
                  </div>
                  <div>
                    <div className="text-xs uppercase tracking-widest text-emerald-300 font-semibold">
                      With FullScale
                    </div>
                    <div className="text-lg font-bold text-foreground">{c.friction.fullscaleLabel}</div>
                  </div>
                </div>
                <ul className="space-y-4">
                  {FRICTION_FULLSCALE.map((item) => {
                    const Icon = item.icon;
                    return (
                      <li key={item.text} className="flex items-start gap-3">
                        <div className="w-8 h-8 rounded-md bg-emerald-400/10 border border-emerald-400/30 flex items-center justify-center flex-shrink-0 mt-0.5">
                          <Icon className="w-4 h-4 text-emerald-300" />
                        </div>
                        <p className="text-sm md:text-base text-foreground/90 leading-relaxed">{item.text}</p>
                      </li>
                    );
                  })}
                </ul>
                <div className="mt-8 pt-6 border-t border-emerald-400/20">
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    Average timeline: <span className="text-emerald-300 font-semibold">{c.friction.statFast}</span>
                    <span className="mx-2 text-muted-foreground/50">·</span>
                    Average cost: <span className="text-emerald-300 font-semibold">{c.friction.statCheap}</span>
                    <span className="mx-2 text-muted-foreground/50">·</span>
                    Outcome: <span className="text-emerald-300 font-semibold">{c.friction.statMeasured}</span>
                  </p>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        </div>
      </section>

      {/* (Brand Partner Strip removed — the single canonical logo cloud
          now lives on the landing page only, so this page no longer
          duplicates the "trusted by" surface.) */}

      {/* Section 3 — "See it in action" — 3-scene Reality-vs-Augmented slider showcase */}
      <section className="relative overflow-hidden py-20">
        {/* Ambient backdrop blurs */}
        <div className="absolute top-0 left-0 w-[500px] h-[500px] bg-emerald-500/10 rounded-full blur-[200px] pointer-events-none" />
        <div className="absolute bottom-0 right-0 w-[500px] h-[500px] bg-emerald-400/10 rounded-full blur-[200px] pointer-events-none" />

        <div className="relative max-w-5xl mx-auto px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12 max-w-3xl mx-auto"
          >
            <Badge
              variant="outline"
              className="mb-5 text-xs font-medium border-emerald-400/40 text-emerald-300 bg-emerald-400/5"
            >
              <Sparkles className="w-3 h-3 mr-1" />
              See It In Action
            </Badge>
            <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4 tracking-tight">
              {c.showcase.title}
            </h2>
            <p className="text-lg text-muted-foreground leading-relaxed">
              {c.showcase.deck}
            </p>
          </motion.div>

          <div className="space-y-16">
            {SHOWCASE_SCENES.map((scene, idx) => (
              <motion.div
                key={scene.testId}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-100px" }}
                transition={{ delay: idx * 0.15, duration: 0.6 }}
                className="space-y-5"
              >
                <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-2">
                  <div>
                    <div className="text-xs uppercase tracking-widest text-emerald-300/80 font-semibold mb-1">
                      {scene.sceneNumber}
                    </div>
                    <h3 className="text-xl md:text-2xl font-bold text-foreground tracking-tight">
                      {scene.label}
                    </h3>
                  </div>
                  <Badge
                    variant="outline"
                    className="text-xs font-medium border-white/15 text-white/70 bg-white/5 self-start sm:self-auto"
                  >
                    <Layers className="w-3 h-3 mr-1" />
                    Drag to Compare
                  </Badge>
                </div>

                <SceneComparisonSlider
                  realityImg={scene.reality}
                  augmentedImg={scene.augmented}
                  realityAlt={scene.realityAlt}
                  augmentedAlt={scene.augmentedAlt}
                  testIdPrefix={scene.testId}
                />

                <p className="text-sm md:text-base text-muted-foreground leading-relaxed max-w-3xl">
                  {scene.description}
                </p>
              </motion.div>
            ))}
          </div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mt-16 max-w-2xl mx-auto"
          >
            <p className="text-sm text-muted-foreground/70">
              Want to see your product in your creator's content? Upload a PNG when you sign up — we'll generate previews for you before you commit anything.
            </p>
          </motion.div>
        </div>
      </section>

      {/* Section 4 — Capabilities */}
      <section className="border-y bg-card/30">
        <div className="max-w-6xl mx-auto px-6 py-20">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12 max-w-3xl mx-auto"
          >
            <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4 tracking-tight">
              {c.capabilities.title}
            </h2>
            <p className="text-lg text-muted-foreground leading-relaxed">
              {c.capabilities.deck}
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {CAPABILITIES.map((cap, idx) => {
              const Icon = cap.icon;
              return (
                <motion.div
                  key={cap.title}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: idx * 0.1, duration: 0.4 }}
                >
                  <Card className="h-full border-emerald-400/10 hover:border-emerald-400/30 transition-all duration-300">
                    <CardContent className="p-6">
                      <div className="w-12 h-12 rounded-xl bg-emerald-400/10 border border-emerald-400/30 flex items-center justify-center mb-4">
                        <Icon className="w-6 h-6 text-emerald-300" />
                      </div>
                      <h3 className="font-semibold text-foreground mb-2 text-base md:text-lg">{cap.title}</h3>
                      <p className="text-sm text-muted-foreground leading-relaxed">{cap.description}</p>
                    </CardContent>
                  </Card>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Section 5 — "How a placement happens" — 4-step process narrative */}
      <section className="max-w-6xl mx-auto px-6 py-20">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center mb-14 max-w-3xl mx-auto"
        >
          <Badge
            variant="outline"
            className="mb-5 text-xs font-medium border-emerald-400/40 text-emerald-300 bg-emerald-400/5"
          >
            <Target className="w-3 h-3 mr-1" />
            The Placement Flow
          </Badge>
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4 tracking-tight">
            {c.steps.title}
          </h2>
          <p className="text-lg text-muted-foreground leading-relaxed">
            {c.steps.deck}
          </p>
        </motion.div>

        {/* Step grid with connecting line on desktop */}
        <div className="relative">
          {/* Desktop-only connecting line */}
          <div className="hidden md:block absolute top-14 left-[12.5%] right-[12.5%] h-px bg-gradient-to-r from-transparent via-emerald-400/30 to-transparent pointer-events-none" />

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 relative">
            {PLACEMENT_STEPS.map((step, idx) => {
              const Icon = step.icon;
              return (
                <motion.div
                  key={step.step}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: idx * 0.1, duration: 0.5 }}
                >
                  <Card className="h-full border-emerald-400/10 hover:border-emerald-400/30 transition-all duration-300 bg-card/40 backdrop-blur-sm">
                    <CardContent className="p-6">
                      {/* Big numbered circle */}
                      <div className="relative inline-flex items-center justify-center w-14 h-14 rounded-full bg-background border-2 border-emerald-400/40 mb-5">
                        <Icon className="w-6 h-6 text-emerald-300" />
                        <div className="absolute -top-1 -right-1 w-6 h-6 rounded-full bg-emerald-500 border-2 border-background flex items-center justify-center text-[11px] font-bold text-white">
                          {idx + 1}
                        </div>
                      </div>
                      <div className="text-xs uppercase tracking-widest text-emerald-300/80 font-semibold mb-2">
                        {step.step}
                      </div>
                      <h3 className="font-semibold text-foreground mb-3 text-lg leading-tight">
                        {step.title}
                      </h3>
                      <p className="text-sm text-muted-foreground leading-relaxed">
                        {step.description}
                      </p>
                    </CardContent>
                  </Card>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Section 6 — Test-and-learn */}
      <section className="max-w-6xl mx-auto px-6 py-20">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center mb-12 max-w-3xl mx-auto"
        >
          <Badge
            variant="outline"
            className="mb-5 text-xs font-medium border-emerald-400/40 text-emerald-300 bg-emerald-400/5"
          >
            <FlaskConical className="w-3 h-3 mr-1" />
            Test & Learn
          </Badge>
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4 tracking-tight">
            {c.testLearn.title}
          </h2>
          <p className="text-lg text-muted-foreground leading-relaxed">
            {c.testLearn.deck}
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {TEST_AND_LEARN.map((feature, idx) => {
            const Icon = feature.icon;
            return (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: idx * 0.12, duration: 0.5 }}
              >
                <Card className="h-full border-emerald-400/10 hover:border-emerald-400/30 transition-all duration-300">
                  <CardContent className="p-7">
                    <div className="flex items-center gap-3 mb-4">
                      <div className="w-10 h-10 rounded-lg bg-emerald-400/10 border border-emerald-400/30 flex items-center justify-center">
                        <Icon className="w-5 h-5 text-emerald-300" />
                      </div>
                      <div className="text-xs uppercase tracking-widest text-emerald-300/80 font-semibold">
                        Step {idx + 1}
                      </div>
                    </div>
                    <h3 className="font-semibold text-foreground mb-3 text-lg">{feature.title}</h3>
                    <p className="text-sm text-muted-foreground leading-relaxed">{feature.description}</p>
                  </CardContent>
                </Card>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* Section 5 — Final sign-up CTA */}
      <section className="relative overflow-hidden">
        {/* Accent gradient backdrop */}
        <div className="absolute inset-0 bg-gradient-to-br from-emerald-500/15 via-background to-emerald-400/5" />
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_rgba(16,185,129,0.12)_0%,_transparent_60%)]" />

        <div className="relative z-10 max-w-4xl mx-auto px-6 py-24 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <div className="inline-flex items-center justify-center w-14 h-14 rounded-2xl bg-emerald-400/15 border border-emerald-400/40 mb-6">
              <Briefcase className="w-7 h-7 text-emerald-300" />
            </div>
            <h2 className="text-3xl md:text-5xl font-bold tracking-tight text-foreground mb-5">
              Ready to put your brand in content that's{" "}
              <span className="bg-gradient-to-r from-emerald-300 via-emerald-400 to-emerald-300 bg-clip-text text-transparent">
                already winning?
              </span>
            </h2>
            <p className="text-lg md:text-xl text-muted-foreground leading-relaxed max-w-2xl mx-auto mb-10">
              {c.finalCta.deck}
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <a
                href="https://airtable.com/app9YlRgIcR9M29p6/pag6tzECkzzXYQoti/form"
                target="_blank"
                rel="noopener noreferrer"
                data-testid="link-brands-final-signup"
              >
                <Button
                  size="lg"
                  className="gap-2 bg-emerald-500 hover:bg-emerald-500/90 text-white shadow-2xl shadow-emerald-500/25 px-8"
                >
                  Apply for Access
                  <ArrowRight className="w-4 h-4" />
                </Button>
              </a>
              <a
                href="mailto:martin@gofullscale.co?subject=Brand%20Interest%20%E2%80%94%20FullScale"
                data-testid="link-brands-final-talk"
              >
                <Button
                  size="lg"
                  variant="outline"
                  className="gap-2 border-emerald-400/40 text-emerald-300 hover:bg-emerald-400/10"
                >
                  <Mail className="w-4 h-4" />
                  Talk to Our Team
                </Button>
              </a>
            </div>
            <p className="text-xs text-muted-foreground/70 mt-8">
              No upfront commitment. Pick a creator, test a placement, see the numbers.
            </p>
          </motion.div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
