import { motion } from "framer-motion";
import {
  FileText,
  Film,
  Mic,
  Wand2,
  ArrowRight,
  Upload,
  Sparkles,
  Layers,
  Clock,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import logoUrl from "@assets/fullscale-logo_1767679525676.png";

const PIPELINE_STEPS = [
  {
    icon: FileText,
    step: "01",
    title: "Upload Your Document",
    description:
      "Drop a PDF or PPTX — pitch decks, reports, proposals. The AI reads every page.",
  },
  {
    icon: Wand2,
    step: "02",
    title: "Story Extraction",
    description:
      "Claude breaks your content into scenes, writes a confident narration script, and identifies the key visuals.",
  },
  {
    icon: Film,
    step: "03",
    title: "AI-Generated Visuals",
    description:
      "Each scene gets a cinematic video clip generated by Seedance — no stock footage, no templates.",
  },
  {
    icon: Mic,
    step: "04",
    title: "Voice & Assembly",
    description:
      "Professional voice narration is synthesized and layered over the visuals into a polished MP4.",
  },
];

const FEATURES = [
  {
    icon: Sparkles,
    title: "AI-Powered",
    description:
      "Every step — story, visuals, voice — is driven by AI. No editing software required.",
  },
  {
    icon: Layers,
    title: "Document In, Video Out",
    description:
      "Upload a pitch deck. Get back a narrated presentation video ready to share.",
  },
  {
    icon: Clock,
    title: "Minutes, Not Weeks",
    description:
      "What used to take a production team and weeks of back-and-forth now happens in minutes.",
  },
  {
    icon: Film,
    title: "Cinematic Quality",
    description:
      "AI-generated scenes with smooth camera motion, professional lighting, and modern style.",
  },
];

export default function FullScaleStudio() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Header */}
      <header className="border-b bg-card/80 backdrop-blur-md sticky top-0 z-30">
        <div className="max-w-6xl mx-auto px-6 py-3 flex items-center justify-between">
          <a href="/">
            <img src={logoUrl} alt="FullScale" className="h-7" />
          </a>
          <div className="flex items-center gap-4">
            <a href="/studio/pricing" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
              Pricing
            </a>
            <a href="/auth?redirect=/studio/upload">
              <Button size="sm" variant="outline" className="gap-1.5 text-xs">
                <Wand2 className="w-3 h-3" />
                Sign In to Studio
              </Button>
            </a>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative min-h-[500px] md:min-h-[600px] overflow-hidden">
        {/* Gradient background */}
        <div className="absolute inset-0 bg-gradient-to-b from-purple-950/40 via-background to-background" />
        <div className="absolute inset-0 bg-gradient-to-br from-primary/8 via-transparent to-purple-500/10" />

        <div className="relative z-10 max-w-6xl mx-auto px-6 pt-24 pb-20">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
            className="text-center max-w-3xl mx-auto"
          >
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-300 text-sm font-medium mb-6 backdrop-blur-sm">
              <Wand2 className="w-4 h-4" />
              FullScale Studio
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight mb-6 text-white">
              Document to Video.
              <br />
              <span className="text-purple-400">Powered by AI.</span>
            </h1>
            <p className="text-lg md:text-xl text-white/70 leading-relaxed max-w-2xl mx-auto mb-8">
              Upload a pitch deck, report, or proposal. Studio reads the
              content, writes a narration, generates cinematic visuals, and
              delivers a polished presentation video — automatically.
            </p>
            <div className="flex items-center justify-center gap-4">
              <a href="/studio/upload">
                <Button size="lg" className="gap-2 bg-purple-600 hover:bg-purple-500">
                  <Upload className="w-4 h-4" />
                  Get Started — It's Free
                </Button>
              </a>
              <Button
                size="lg"
                variant="outline"
                className="gap-2 border-white/20 text-white hover:bg-white/10"
                onClick={() => {
                  document
                    .getElementById("how-it-works")
                    ?.scrollIntoView({ behavior: "smooth" });
                }}
              >
                How It Works
                <ArrowRight className="w-4 h-4" />
              </Button>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="border-y bg-card/30">
        <div className="max-w-6xl mx-auto px-6 py-16">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12"
          >
            <h2 className="text-2xl md:text-3xl font-bold text-foreground mb-3">
              What Studio Does
            </h2>
            <p className="text-muted-foreground max-w-lg mx-auto">
              A fully automated pipeline that turns static documents into
              dynamic video presentations
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {FEATURES.map((feature, idx) => {
              const Icon = feature.icon;
              return (
                <motion.div
                  key={feature.title}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: idx * 0.1, duration: 0.4 }}
                >
                  <Card className="h-full border-white/5 hover:border-purple-500/20 transition-all duration-300">
                    <CardContent className="p-6">
                      <div className="w-12 h-12 rounded-xl bg-purple-500/10 flex items-center justify-center mb-4">
                        <Icon className="w-6 h-6 text-purple-400" />
                      </div>
                      <h3 className="font-semibold text-foreground mb-2">
                        {feature.title}
                      </h3>
                      <p className="text-sm text-muted-foreground leading-relaxed">
                        {feature.description}
                      </p>
                    </CardContent>
                  </Card>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* How It Works — Pipeline Steps */}
      <section className="max-w-6xl mx-auto px-6 py-16" id="how-it-works">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center mb-12"
        >
          <h2 className="text-2xl md:text-3xl font-bold text-foreground mb-3">
            How It Works
          </h2>
          <p className="text-muted-foreground max-w-lg mx-auto">
            Four stages. One upload. No editing required.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-4xl mx-auto">
          {PIPELINE_STEPS.map((step, idx) => {
            const Icon = step.icon;
            return (
              <motion.div
                key={step.step}
                initial={{ opacity: 0, x: idx % 2 === 0 ? -20 : 20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: idx * 0.12, duration: 0.5 }}
              >
                <Card className="h-full border-white/5 hover:border-purple-500/20 transition-all duration-300">
                  <CardContent className="p-6 flex gap-5">
                    <div className="flex-shrink-0">
                      <div className="w-14 h-14 rounded-2xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center">
                        <Icon className="w-6 h-6 text-purple-400" />
                      </div>
                    </div>
                    <div>
                      <p className="text-xs font-mono text-purple-400/60 mb-1">
                        STEP {step.step}
                      </p>
                      <h3 className="font-semibold text-foreground mb-1.5">
                        {step.title}
                      </h3>
                      <p className="text-sm text-muted-foreground leading-relaxed">
                        {step.description}
                      </p>
                    </div>
                  </CardContent>
                </Card>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* CTA Section */}
      <section className="border-y bg-gradient-to-r from-purple-500/5 via-transparent to-primary/5">
        <div className="max-w-4xl mx-auto px-6 py-20 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
          >
            <h2 className="text-2xl md:text-3xl font-bold text-foreground mb-4">
              Ready to Turn Your Deck Into a Video?
            </h2>
            <p className="text-muted-foreground max-w-md mx-auto mb-8">
              Upload a PDF or PPTX and let Studio handle the rest. Your first
              video is free.
            </p>
            <div className="flex items-center justify-center gap-4 flex-wrap">
              <a href="/studio/upload">
                <Button size="lg" className="gap-2 bg-purple-600 hover:bg-purple-500">
                  <Upload className="w-4 h-4" />
                  Start Creating
                </Button>
              </a>
              <a href="/studio/pricing">
                <Button size="lg" variant="outline" className="gap-2 border-purple-500/30 text-purple-300 hover:bg-purple-500/10">
                  View Pricing
                </Button>
              </a>
              <a href="/content">
                <Button size="lg" variant="ghost" className="gap-2 text-white/60 hover:text-white hover:bg-white/5">
                  Explore Creates
                  <ArrowRight className="w-4 h-4" />
                </Button>
              </a>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t py-8">
        <div className="max-w-6xl mx-auto px-6 flex items-center justify-between">
          <p className="text-sm text-muted-foreground">
            Powered by{" "}
            <a href="/" className="text-primary font-medium hover:underline">
              FullScale
            </a>
          </p>
          <img src={logoUrl} alt="FullScale" className="h-5 opacity-40" />
        </div>
      </footer>
    </div>
  );
}
